# Generated by Django 3.2.19 on 2023-05-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('client_company', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('client_type', models.CharField(choices=[('ARC', 'Architect'), ('PLM', 'Plumbing Contractor'), ('DVP', 'Developer'), ('EPC', 'EPC Contractor'), ('CLN', 'End-Client')], default='CLN', max_length=55)),
                ('address1', models.CharField(max_length=55)),
                ('address2', models.CharField(max_length=55)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager_clients', to='team.manager')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sar_clients', to='team.sar')),
            ],
            options={
                'db_table': 'Client.Client',
                'ordering': ['client_company'],
            },
        ),
    ]
