# Generated by Django 3.2.19 on 2023-07-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20230702_2105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client.Client',
        ),
    ]
