# Generated by Django 3.2.19 on 2023-07-05 12:57

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_sar_manager'),
        ('client', '0006_auto_20230705_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(on_delete=models.SET(client.models.get_manager), related_name='clients', to='team.manager'),
        ),
        migrations.AlterField(
            model_name='client',
            name='salesman',
            field=models.ForeignKey(on_delete=models.SET(client.models.get_salesman), related_name='clients', to='team.sar'),
        ),
    ]
