# Generated by Django 3.2.19 on 2023-05-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(verbose_name=100)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TBD', 'To-be-Done'), ('D', 'Done')], max_length=50)),
                ('priority', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgent')], default='Normal', max_length=50)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_tasks', to='team.sar')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
