# Generated by Django 3.2.19 on 2023-06-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20230601_2323'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.sar'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.CharField(choices=[('TBD', 'To Do'), ('D', 'Done')], default='To Do', max_length=50),
        ),
    ]
