# Generated by Django 3.2.19 on 2023-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20230601_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
