# Generated by Django 3.2.19 on 2023-07-05 13:16

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_sar_manager'),
        ('task_manager', '0004_alter_taskmanager_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='assigned_to',
            field=models.ForeignKey(on_delete=models.SET(task_manager.models.get_salesman), related_name='tasks', to='team.sar'),
        ),
    ]
