# Generated by Django 3.2.19 on 2023-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_taskmanager_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='due_date',
            field=models.DateField(),
        ),
    ]
