# Generated by Django 3.2.19 on 2023-06-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sar',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'Sars'},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='mng_id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='sar',
            name='sar_id',
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sar',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sars', to='team.manager'),
        ),
    ]
