# Generated by Django 3.2.19 on 2023-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20230601_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sar',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'Sars'},
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sar',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
