# Generated by Django 3.2.19 on 2023-07-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20230625_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sar',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sars', to='team.manager'),
            preserve_default=False,
        ),
    ]
