# Generated by Django 3.2.19 on 2023-07-05 12:57

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_sar_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sar',
            name='manager',
            field=models.ForeignKey(on_delete=models.SET(team.models.get_manager), related_name='sars', to='team.manager'),
        ),
    ]
