# Generated by Django 3.2.19 on 2023-05-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(max_length=10, unique=True)),
                ('brand', models.TextField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10, unique=True)),
                ('category', models.TextField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type_of_construction', models.CharField(choices=[('NC', 'New Construction'), ('RF', 'Refurbishment')], max_length=20)),
                ('project_status', models.TextField(choices=[('Atv', 'Active'), ('O/h', 'On hold'), ('P.won', 'Partially won'), ('Won', 'Won')], default='Active', max_length=55)),
                ('est_closing_date', models.DateField()),
                ('est_date_of_delivery', models.DateField()),
                ('potential_value', models.FloatField()),
                ('winning_chance', models.DecimalField(choices=[(0.0, 'No Chance'), (0.2, 'Very Low'), (0.5, 'May be'), (0.75, 'Highly Likely'), (0.9, 'WON PENDING PO'), (1.0, 'WON with PO')], decimal_places=2, max_digits=3)),
                ('forecast_pxp', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_projects', to='project.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='project.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='client.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_projects', to='team.manager')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesman_projects', to='team.sar')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
