# Generated by Django 3.2.19 on 2023-06-03 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_forecast_pxp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='winning_chance',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0% - No Chance'), (Decimal('0.20'), '20% - Very Low, 20%'), (Decimal('0.50'), '50% - May be'), (Decimal('0.75'), '75% - Highly Likely'), (Decimal('0.90'), '90% - WON PENDING PO'), (Decimal('1.00'), '100% - WON with PO')], decimal_places=2, max_digits=3),
        ),
    ]
