# Generated by Django 3.2.19 on 2023-07-10 14:59

from decimal import Decimal
from django.db import migrations, models
import lead_master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='LeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type_of_construction', models.CharField(choices=[('NC', 'New Construction'), ('RF', 'Refurbishment')], max_length=20)),
                ('lead_status', models.TextField(choices=[('Atv', 'Active'), ('O/h', 'On hold'), ('P.won', 'Partially won'), ('Won', 'Won')], default='Active', max_length=55)),
                ('est_closing_date', models.DateField()),
                ('est_date_of_delivery', models.DateField()),
                ('potential_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('winning_chance', models.DecimalField(choices=[(Decimal('0.00'), '0% - No Chance'), (Decimal('0.20'), '20% - Very Low'), (Decimal('0.50'), '50% - May be'), (Decimal('0.75'), '75% - Highly Likely'), (Decimal('0.90'), '90% - WON PENDING PO'), (Decimal('1.00'), '100% - WON with PO')], decimal_places=2, max_digits=3)),
                ('forecast_pxp', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=models.SET(lead_master.models.get_brand), related_name='lead_masters', to='lead_master.brand')),
                ('category', models.ForeignKey(on_delete=models.SET(lead_master.models.get_category), related_name='lead_masters', to='lead_master.category')),
                ('client', models.ForeignKey(on_delete=models.SET(lead_master.models.get_client), related_name='lead_masters', to='client.client')),
                ('manager', models.ForeignKey(on_delete=models.SET(lead_master.models.get_manager), related_name='lead_masters', to='team.manager')),
                ('salesman', models.ForeignKey(on_delete=models.SET(lead_master.models.get_salesman), related_name='lead_masters', to='team.sar')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
