# Generated by Django 3.2.19 on 2023-07-05 12:57

from django.db import migrations, models
import lead_master.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20230705_1257'),
        ('team', '0005_alter_sar_manager'),
        ('lead_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='brand',
            field=models.ForeignKey(on_delete=models.SET(lead_master.models.get_brand), related_name='lead_masters', to='lead_master.brand'),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(lead_master.models.get_category), related_name='lead_masters', to='lead_master.category'),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='client',
            field=models.ForeignKey(on_delete=models.SET(lead_master.models.get_client), related_name='lead_masters', to='client.client'),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='manager',
            field=models.ForeignKey(on_delete=models.SET(lead_master.models.get_manager), related_name='lead_masters', to='team.manager'),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='salesman',
            field=models.ForeignKey(on_delete=models.SET(lead_master.models.get_salesman), related_name='lead_masters', to='team.sar'),
        ),
    ]
