# Generated by Django 3.2.19 on 2023-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_master', '0002_auto_20230705_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='forecast_pxp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='potential_value',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
